import os,json,uuid,zipfile,shutil,re,base64
from pathlib import Path
from datetime import datetime,timezone
from fastapi import FastAPI,UploadFile,File,HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel

DATA=Path(os.getenv("DATA_DIR","./data")); DATA.mkdir(parents=True,exist_ok=True)
PROJECTS=DATA/"projects"; PROJECTS.mkdir(exist_ok=True)
UPLOADS=DATA/"uploads"; UPLOADS.mkdir(exist_ok=True)
MEMORY=DATA/"memory.json"
if not MEMORY.exists(): MEMORY.write_text(json.dumps({"messages":[],"facts":[]},indent=2),encoding="utf8")

origins=os.getenv("CORS_ORIGINS","*").split(",")
app=FastAPI(title="The Haven Engine",version="2.0")
app.add_middleware(CORSMiddleware,allow_origins=origins,allow_credentials=False,allow_methods=["*"],allow_headers=["*"])

class Chat(BaseModel):
    message:str
    files:list[str]=[]
class Build(BaseModel):
    name:str="haven-project"
    kind:str="auto"
    request:str
    files:dict[str,str]={}

LANG={
 "html":["html","htm"],"css":["css"],"javascript":["js","mjs","cjs"],"typescript":["ts","tsx"],"python":["py"],"java":["java"],"c":["c","h"],"cpp":["cpp","cc","cxx","hpp"],"csharp":["cs"],"rust":["rs"],"go":["go"],"php":["php"],"ruby":["rb"],"swift":["swift"],"kotlin":["kt","kts"],"sql":["sql"],"json":["json"],"yaml":["yml","yaml"],"markdown":["md"]
}
KNOWLEDGE={
 "github": "GitHub is best used here for source code and versioned backups. Large binary assets should not be treated as unlimited repository memory.",
 "render": "Render runs the dynamic Haven Engine. A persistent disk preserves files across deploys and restarts; the disk must be mounted at the DATA_DIR path.",
 "storage": "The Haven stores chat memory, project JSON, uploaded files, and generated ZIPs under DATA_DIR. Production scaling should move shared data to a managed database/object store.",
 "accuracy": "The Haven is deterministic rather than generative AI. It improves reliability through schemas, templates, validators, tests, manifests, and reproducible builds.",
 "bad message": "The Haven downloads generated projects from the Render API as application/zip with Content-Disposition, instead of opening generated text files as unsupported browser documents."
}
def now(): return datetime.now(timezone.utc).isoformat()
def readmem():
    try:return json.loads(MEMORY.read_text(encoding="utf8"))
    except:return {"messages":[],"facts":[]}
def writemem(x): MEMORY.write_text(json.dumps(x,indent=2,ensure_ascii=False),encoding="utf8")
def remember(role,text):
    m=readmem();m["messages"].append({"time":now(),"role":role,"text":text})
    m["messages"]=m["messages"][-2000:];writemem(m)

def extlang(path):
    ext=Path(path).suffix.lower().lstrip(".")
    for lang,exts in LANG.items():
        if ext in exts:return lang
    return "unknown"

def tree(files):
    lines=[]
    for name in sorted(files):
        parts=Path(name).parts
        lines.append("  "*max(0,len(parts)-1)+"└─ "+parts[-1]+" ["+extlang(name)+"]")
    return "\n".join(lines)

def generate(kind,request):
    r=request.lower()
    if kind=="auto":
        kind="game" if any(x in r for x in ["game","racing","player","enemy","score","joystick"]) else "web"
    if kind in ("game","web","static"):
        game=kind=="game"
        return {
          "index.html":"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The Haven Project</title><link rel="stylesheet" href="styles.css"></head><body><main><h1>The Haven Project</h1><p id="description"></p>"""+("""<canvas id="game" width="900" height="500"></canvas>""" if game else """<section id="app"></section>""")+"""</main><script src="app.js"></script></body></html>""",
          "styles.css":"body{margin:0;background:#080d18;color:#eef2ff;font-family:system-ui}main{width:min(900px,92%);margin:40px auto;text-align:center}canvas{max-width:100%;background:#020617;border:1px solid #334155;border-radius:12px}",
          "app.js":("const c=document.querySelector('#game'),x=c.getContext('2d');let p={x:80,y:220},k={};addEventListener('keydown',e=>k[e.key.toLowerCase()]=1);addEventListener('keyup',e=>k[e.key.toLowerCase()]=0);function loop(){p.x+=((k.d||k.arrowright)?4:0)-((k.a||k.arrowleft)?4:0);p.y+=((k.s||k.arrowdown)?4:0)-((k.w||k.arrowup)?4:0);p.x=Math.max(0,Math.min(c.width-30,p.x));p.y=Math.max(0,Math.min(c.height-30,p.y));x.clearRect(0,0,c.width,c.height);x.fillStyle='#60a5fa';x.fillRect(p.x,p.y,30,30);requestAnimationFrame(loop)}loop();"
          if game else "document.querySelector('#description').textContent="+json.dumps(request)+";document.querySelector('#app').innerHTML='<p>Project generated by The Haven deterministic engine.</p>';")
        }
    if kind=="node":
        return {"package.json":json.dumps({"name":"haven-project","version":"1.0.0","private":True,"scripts":{"start":"node src/index.js"}},indent=2),"src/index.js":"console.log("+json.dumps(request)+");"}
    if kind=="python":
        return {"app.py":"print("+repr(request)+")","requirements.txt":"# Add third-party packages here as needed.\n"}
    return {"README.md":"The Haven project\\n\\n"+request}

@app.get("/health")
def health(): return {"ok":True,"service":"the-haven-engine","version":"2.0","time":now()}

@app.post("/chat")
def chat(c:Chat):
    remember("user",c.message)
    q=c.message.lower()
    if "github" in q: reply=KNOWLEDGE["github"]
    elif "render" in q or "persistent" in q: reply=KNOWLEDGE["render"]
    elif "storage" in q or "memory" in q: reply=KNOWLEDGE["storage"]
    elif "accurate" in q or "100%" in q: reply=KNOWLEDGE["accuracy"]
    elif "bad message" in q or "download" in q: reply=KNOWLEDGE["bad message"]
    elif "file" in q or "folder" in q: reply="I can inspect the supplied project file names, classify them by language, and build a deterministic project tree. Current files: "+(", ".join(c.files) if c.files else "none.")
    else: reply="The Haven Engine received your question. I am a deterministic rules-and-knowledge engine, not a generative AI. I can explain supported engineering concepts, inspect project structure, and run the build pipeline. For new capabilities, add a rule/template/validator to the engine."
    remember("assistant",reply)
    return {"reply":reply}

@app.post("/projects/build")
def build(b:Build):
    pid=str(uuid.uuid4()); p=PROJECTS/pid;p.mkdir()
    generated=generate(b.kind,b.request)
    # User files are copied into a safe source directory; generated files win only on exact collision.
    for n,v in b.files.items():
        n=n.replace("\\","/")
        if ".." in Path(n).parts or n.startswith("/"): continue
        if n not in generated: generated[n]=v if isinstance(v,str) else str(v)
    manifest={"project_id":pid,"name":b.name,"request":b.request,"created_at":now(),"files":sorted(generated),"tree":tree(generated)}
    (p/"manifest.json").write_text(json.dumps(manifest,indent=2),encoding="utf8")
    (p/"files.json").write_text(json.dumps(generated,indent=2,ensure_ascii=False),encoding="utf8")
    return {"project_id":pid,"files":generated,"manifest":manifest}

@app.get("/projects/{pid}/download")
def download(pid:str):
    p=PROJECTS/pid
    if not p.exists(): raise HTTPException(404,"Project not found")
    data=json.loads((p/"files.json").read_text(encoding="utf8"))
    z=p/"The-Haven-Project.zip"
    with zipfile.ZipFile(z,"w",zipfile.ZIP_DEFLATED) as out:
        for n,v in data.items(): out.writestr(n,v)
        out.writestr("HAVEN-MANIFEST.json",(p/"manifest.json").read_text(encoding="utf8"))
    return FileResponse(z,media_type="application/zip",filename="The-Haven-Project.zip")

@app.post("/uploads")
async def uploads(files:list[UploadFile]=File(...)):
    saved=[]
    for f in files:
        uid=str(uuid.uuid4()); safe=Path(f.filename or "upload.bin").name
        dest=UPLOADS/(uid+"-"+safe)
        with dest.open("wb") as out: shutil.copyfileobj(f.file,out)
        saved.append({"id":uid,"name":safe,"size":dest.stat().st_size})
    return {"saved":saved}
